global using System.Buffers;
global using System.Collections.Immutable;
global using System.Diagnostics.CodeAnalysis;
global using Enhanced.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection;
global using unicfg.Base.Analysis;
global using unicfg.Base.Environment;
global using unicfg.Base.Extensions;
global using unicfg.Base.Inputs;
global using unicfg.Base.Primitives;
global using unicfg.Base.SyntaxTree;
global using unicfg.Base.SyntaxTree.Values;
global using static unicfg.Uni.DiagnosticDescriptors;
